import { Mole } from '../types'

export const normalScore = 10

export const missScore = -50

export const MolePopList: Mole[] = [
  { time: 1, img: 'images/mogura_ai.png', score: normalScore, holePos: 6 },
  { time: 1, img: 'images/mogura_komaru.png', score: normalScore, holePos: 4 },
  { time: 1, img: 'images/mogura_misaki.png', score: normalScore, holePos: 8 },
  { time: 2, img: 'images/mogura_kojima.png', score: normalScore, holePos: 5 },
  { time: 2, img: 'images/mogura_koutaro.png', score: normalScore, holePos: 7 },
  { time: 3, img: 'images/mogura_nonakasan.png', score: missScore, holePos: 5 },
  { time: 3, img: 'images/mogura_komaru.png', score: normalScore, holePos: 3 },
  { time: 3, img: 'images/mogura_ai.png', score: normalScore, holePos: 1 },
  { time: 4, img: 'images/mogura_kojima.png', score: normalScore, holePos: 7 },
  { time: 4, img: 'images/mogura_misaki.png', score: normalScore, holePos: 5 },
  { time: 5, img: 'images/mogura_ai.png', score: normalScore, holePos: 2 },
  { time: 5, img: 'images/mogura_koutaro.png', score: normalScore, holePos: 8 },
  { time: 6, img: 'images/mogura_kojima.png', score: normalScore, holePos: 3 },
  { time: 6, img: 'images/mogura_komaru.png', score: normalScore, holePos: 6 },
  { time: 6, img: 'images/mogura_misaki.png', score: normalScore, holePos: 4 },
  { time: 6, img: 'images/mogura_nonakasan.png', score: missScore, holePos: 8 },
  { time: 7, img: 'images/mogura_kojima.png', score: normalScore, holePos: 1 },
  { time: 8, img: 'images/mogura_ai.png', score: normalScore, holePos: 7 },
  { time: 8, img: 'images/mogura_koutaro.png', score: normalScore, holePos: 4 },
  {
    time: 8,
    img: 'images/mogura_nonakasan.png',
    score: normalScore,
    holePos: 6,
  },
  { time: 9, img: 'images/mogura_kojima.png', score: normalScore, holePos: 3 },
  { time: 10, img: 'images/mogura_komaru.png', score: normalScore, holePos: 2 },
  { time: 10, img: 'images/mogura_misaki.png', score: normalScore, holePos: 5 },
  { time: 11, img: 'images/mogura_ai.png', score: normalScore, holePos: 6 },
  {
    time: 11,
    img: 'images/mogura_koutaro.png',
    score: normalScore,
    holePos: 9,
  },
  {
    time: 11,
    img: 'images/mogura_nonakasan.png',
    score: missScore,
    holePos: 2,
  },
  { time: 13, img: 'images/mogura_kojima.png', score: normalScore, holePos: 1 },
  {
    time: 13,
    img: 'images/mogura_koutaro.png',
    score: normalScore,
    holePos: 8,
  },
  { time: 14, img: 'images/mogura_komaru.png', score: normalScore, holePos: 4 },
  { time: 14, img: 'images/mogura_misaki.png', score: normalScore, holePos: 3 },
  {
    time: 14,
    img: 'images/mogura_nonakasan.png',
    score: missScore,
    holePos: 8,
  },
  { time: 15, img: 'images/mogura_ai.png', score: normalScore, holePos: 2 },
  { time: 16, img: 'images/mogura_komaru.png', score: normalScore, holePos: 7 },
  { time: 17, img: 'images/mogura_kojima.png', score: normalScore, holePos: 6 },
  {
    time: 17,
    img: 'images/mogura_koutaro.png',
    score: normalScore,
    holePos: 1,
  },
  { time: 17, img: 'images/mogura_misaki.png', score: normalScore, holePos: 5 },
  {
    time: 17,
    img: 'images/mogura_nonakasan.png',
    score: missScore,
    holePos: 7,
  },
  { time: 18, img: 'images/mogura_misaki.png', score: normalScore, holePos: 7 },
  { time: 19, img: 'images/mogura_ai.png', score: normalScore, holePos: 3 },
  {
    time: 19,
    img: 'images/mogura_koutaro.png',
    score: normalScore,
    holePos: 2,
  },
  { time: 20, img: 'images/mogura_kojima.png', score: normalScore, holePos: 8 },
  { time: 20, img: 'images/mogura_komaru.png', score: normalScore, holePos: 4 },
  { time: 21, img: 'images/mogura_ai.png', score: normalScore, holePos: 7 },
  { time: 21, img: 'images/mogura_misaki.png', score: normalScore, holePos: 6 },
  { time: 22, img: 'images/mogura_kojima.png', score: normalScore, holePos: 2 },
  {
    time: 22,
    img: 'images/mogura_koutaro.png',
    score: normalScore,
    holePos: 8,
  },
  {
    time: 22,
    img: 'images/mogura_nonakasan.png',
    score: missScore,
    holePos: 1,
  },
  { time: 23, img: 'images/mogura_kojima.png', score: normalScore, holePos: 3 },
  { time: 23, img: 'images/mogura_misaki.png', score: normalScore, holePos: 6 },
  {
    time: 23,
    img: 'images/mogura_nonakasan.png',
    score: missScore,
    holePos: 5,
  },
  {
    time: 25,
    img: 'images/mogura_koutaro.png',
    score: normalScore,
    holePos: 5,
  },
  { time: 25, img: 'images/mogura_ai.png', score: normalScore, holePos: 8 },
  {
    time: 25,
    img: 'images/mogura_nonakasan.png',
    score: missScore,
    holePos: 4,
  },
  {
    time: 26,
    img: 'images/mogura_nonakasan.png',
    score: missScore,
    holePos: 3,
  },
  { time: 26, img: 'images/mogura_komaru.png', score: normalScore, holePos: 6 },
  { time: 26, img: 'images/mogura_misaki.png', score: normalScore, holePos: 5 },
  {
    time: 27,
    img: 'images/mogura_koutaro.png',
    score: normalScore,
    holePos: 3,
  },
  { time: 27, img: 'images/mogura_kojima.png', score: normalScore, holePos: 7 },
  {
    time: 28,
    img: 'images/mogura_nonakasan.png',
    score: missScore,
    holePos: 6,
  },
  { time: 30, img: 'images/mogura_ai.png', score: normalScore, holePos: 4 },
  { time: 30, img: 'images/mogura_kojima.png', score: normalScore, holePos: 6 },
  { time: 30, img: 'images/mogura_komaru.png', score: normalScore, holePos: 5 },
  {
    time: 30,
    img: 'images/mogura_koutaro.png',
    score: normalScore,
    holePos: 2,
  },
  { time: 30, img: 'images/mogura_misaki.png', score: normalScore, holePos: 1 },
]

export enum ScreenProgress {
  START,
  GAME,
}

export const timerSecond = 30
