export const areas = [
  {
    id: 'hokkaido-touhoku',
    name: '北海道・東北',
    prefectures: [
      'hokkaido',
      'aomori',
      'akita',
      'iwate',
      'yamagata',
      'miyagi',
      'fukushima',
    ],
  },
  {
    id: 'kantou',
    name: '関東',
    prefectures: [
      'gunma',
      'tochigi',
      'ibaraki',
      'saitama',
      'chiba',
      'tokyo',
      'kanagawa',
    ],
  },
  {
    id: 'tyubu',
    name: '中部',
    prefectures: [
      'nigata',
      'toyama',
      'ishikawa',
      'fukui',
      'nagano',
      'gifu',
      'yamanashi',
      'aichi',
      'shizuoka',
    ],
  },
  {
    id: 'kinki',
    name: '近畿',
    prefectures: [
      'kyoto',
      'shiga',
      'osaka',
      'nara',
      'mie',
      'wakayama',
      'hyougo',
    ],
  },
  {
    id: 'tyugoku',
    name: '中国',
    prefectures: ['tottori', 'okayama', 'shimane', 'hiroshima', 'yamaguchi'],
  },
  {
    id: 'shikoku',
    name: '四国',
    prefectures: ['kagawa', 'ehime', 'tokushima', 'kouchi'],
  },
  {
    id: 'kyusyu',
    name: '九州・沖縄',
    prefectures: [
      'fukuoka',
      'saga',
      'nagasaki',
      'oita',
      'kumamoto',
      'miyazaki',
      'kagoshima',
      'okinawa',
    ],
  },
]

export const prefectures: { [key in string]: string } = {
  hokkaido: '北海道',
  aomori: '青森',
  akita: '秋田',
  iwate: '岩手',
  yamagata: '山形',
  miyagi: '宮城',
  fukushima: '福島',
  gunma: '群馬',
  tochigi: '栃木',
  ibaraki: '茨城',
  saitama: '埼玉',
  chiba: '千葉',
  tokyo: '東京',
  kanagawa: '神奈川',
  nigata: '新潟',
  toyama: '富山',
  ishikawa: '石川',
  fukui: '福井',
  nagano: '長野',
  gifu: '岐阜',
  yamanashi: '山梨',
  aichi: '愛知',
  shizuoka: '静岡',
  kyoto: '京都',
  shiga: '滋賀',
  osaka: '大阪',
  nara: '奈良',
  mie: '三重',
  wakayama: '和歌山',
  hyougo: '兵庫',
  tottori: '鳥取',
  shimane: '島根',
  okayama: '岡山',
  hiroshima: '広島',
  yamaguchi: '山口',
  kagawa: '香川',
  ehime: '愛媛',
  tokushima: '徳島',
  kouchi: '高知',
  fukuoka: '福岡',
  saga: '佐賀',
  nagasaki: '長崎',
  oita: '大分',
  kumamoto: '熊本',
  miyazaki: '宮崎',
  kagoshima: '鹿児島',
  okinawa: '沖縄',
}
